name: codegen

on:
  push:
    branches: [0.6]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    # container: 
    #   image: rustropy/rust-wasm-ci
    #   options: --user root
    services:
      registry:
        image: registry:2.7
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - id: run-nats
        uses: wasmcloud/common-actions/run-nats@main
        with:
          options: '-js'
      - name: install wasm-cloud
        run: |
          bash install_wasmcloud.sh
          ls
          WASMCLOUD_HOST_SEED=SNAKDMBLB7TPIL4K3YXDGLUDXYFEEB2UAUXSAJYFBUKAWXBT6VPSTSE34Y WASMCLOUD_OCI_ALLOWED_INSECURE=localhost:5000 ./bin/wasmcloud_host start
      - uses: actions/cache@v2
        id: cargo-cache
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            templates/target/
            templates/www/target/
          key: ${{ runner.os }}-cargo1-${{ hashFiles('templates/Cargo.lock') }}-${{ hashFiles('templates/www/Cargo.lock') }}
      - uses: actions/cache@v2
        id: cargo-bin-cache
        with:
          path: |
            ~/.cargo/bin/
            /usr/local/bin/wash
          key: ${{ runner.os }}-cargo1 }}
      # - name: a
      #   run:  && 
      - name: cargo/bin
        run: ls ~/.cargo/bin/
      - name: ls
        run: ls templates/www
      - name: source profile
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
         
      - name: Install neccessary tool
        env:
          CACHE_HIT: ${{steps.cargo-bin-cache.outputs.cache-hit}}
        run: |
          if [[ "$CACHE_HIT" != 'true' ]]; then
            sudo apt-get install libcurl4-openssl-dev
            curl -s https://packagecloud.io/install/repositories/wasmcloud/core/script.deb.sh | sudo bash && sudo apt install wash
            which wash
            ls ~
          fi
          wasm-bindgen --version || { cargo install -f wasm-bindgen-cli --vers 0.2.83;}
          cargo make --version || { cargo install -f cargo-make;}
          basic-http-server --version || { cargo install -f basic-http-server;}
          wasm-snip --version || { cargo install -f wasm-snip;}
      - name: install wasm-snip
        run: wasm-snip --version || { cargo install -f wasm-snip;}
      - name: install-wasm32
        run: rustup target add wasm32-unknown-unknown
      - name: cat host
        run: cat host_config.json
        #run: sudo apt install wasmcloud wash
      - name: make build
        working-directory: ./templates
        run: |
          ls
          make reg_host=${{ job.services.registry.ports['5000'] }} build
      - name: cat logs
        run: |
          ls
          cat nohup.out
      - name: make start
        working-directory: ./templates
        run: make reg_host=${{ job.services.registry.ports['5000'] }} start

      # - name: Collect docker logs on failure
      #   uses: jwalton/gh-docker-logs@v1
      #   with:
      #     images: 'wasmcloud/wasmcloud_host:latest'
      #     dest: './logs'
      # - name: Tar logs
      #   run: tar cvzf ./logs.tgz ./logs
      # - name: Upload logs to GitHub
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: logs.tgz
      #     path: ./logs.tgz
      # - name: wash
      #   run: wash ctl get hosts
      # - name: kill
      #   run: sudo netstat -ltnup | grep ':4000'
      # - name: build_ui
      #   uses: marcopolo/cargo@master
      #   with:
      #     command: make
      #     args: wasm-bindgen
      #     working-directory: ./templates/www
      # - name: serve_ui
      #   working-directory: ./templates/www
      #   run: cargo make wasm-serve2
      # - name: ngrok install
      #   run: |
      #     curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null &&
      #     echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list &&
      #     sudo apt update && sudo apt install ngrok   
      # - name: save authtoken
      #   run: |
      #     ngrok authtoken ${{ secrets.NGROK_AUTHTOKEN }}
      # - name: start ngrok
      #   run: |
      #     ngrok http 4001 --log=stdout > ngrok.log &
      # - name: sleep
      #   run: |
      #     bash sleep.sh 10s
      # - name: ngrok
      #   run: cat ngrok.log
      # - name: sleep
      #   run: |
      #     bash sleep.sh 20m

      # - name: download_wasmcloud_host
      #   run: wget -c https://github.com/wasmCloud/wasmcloud-otp/releases/download/v0.50.3/x86_64-linux.tar.gz -O - | tar -xz
      # - name: ls
      #   run: ls bin
      # - name: run
      #   run: WASMCLOUD_CLUSTER_SEED=SCABKLLO4OZAT4WERZ2BC4NDFHNUJO6WOGHVG4JLKPFUVJLHAP4WQWWSJ4 WASMCLOUD_CLUSTER_ISSUERS=CBLXC6GW777ZB4EZBVDWJ7AJHA5R4TIN7GQC32XMCDA4NIPQQTPY3SVP WASMCLOUD_OCI_ALLOWED_INSECURE=localhost:5000 ./bin/wasmcloud_host
